config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  get 'users/index' => 'users#index'
  get 'users/security' => 'users#security'
  get 'users/techsupport' => 'users#techsupport'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: "rasp", password: "shh" 
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phn)
    end
    
    def security
    end
    
    def techsupport
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iotapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="/materialize.min.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="/external.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="/switch.css"  media="screen,projection"/>
  
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

<!--Import jQuery before materialize.js-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="/assets/materialize.min.js"></script>

</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phn %><br>
    <%= f.text_field :phn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- Nav Bar and Slider code begins -->
<nav class = "black ">
  <ul class="right hide-on-med-and-down">
    <!-- <a href="#" class="brand-logo center">IOT App</a> -->
    <img src="/assets/logo2small.png" class="brand-logo center"></img>
    <!--<li><a href="#!">Second Sidebar Link</a></li> -->
  </ul>
  <ul id="slide-out" class="side-nav linepadding">
    <li> <%= link_to "Home Automation" , root_path %>  </li>
    <hr width =80%>
    <li> <%= link_to "Security", users_security_path %>  </li>
    <li > <div class="techsupport" ><hr width =80%> <div class="orange "> <%= link_to "Tech Support", users_techsupport_path %></div> </div> </li>
    
    
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons iconpadding">menu</i></a>
</nav>
<!-- slider code ends here -->
<!-- Rooms lights and fans part begins here -->  
  
  <div class = "container "> 
        <h4 class ="center thin" > Room 1 </h4> 
        <div class="collection">
          <a href="#!" class="collection-item">Light
                  <span class="badge">     
                      <!-- Switch -->
                      <div class="switch">
                        <label>
                          Off
                        <input type="checkbox">
                        <span class="lever"></span>
                          On
                        </label>
                      </div>
                  </span> 
          </a>
          <a href="#!" class="collection-item">Fan
                  <span class="badge">     
                      <!-- Switch -->
                      <div class="switch">
                        <label>
                          Off
                        <input type="checkbox">
                        <span class="lever"></span>
                          On
                        </label>
                      </div>
                  </span> 
          </a>
        </div>

        <h4 class ="center thin"> Room 2 </h4> 
        <div class="collection">
          <a href="#!" class="collection-item">Light
                  <span class="badge">     
                      <!-- Switch -->
                      <div class="switch">
                        <label>
                          Off
                        <input type="checkbox">
                        <span class="lever"></span>
                          On
                        </label>
                      </div>
                  </span> 
          </a>
          <a href="#!" class="collection-item">Fan
                  <span class="badge">     
                      <!-- Switch -->
                      <div class="switch">
                        <label>
                          Off
                        <input type="checkbox">
                        <span class="lever"></span>
                          On
                        </label>
                      </div>
                  </span> 
          </a>
        </div>
        
        <h4 class ="center thin"> Front Yard </h4> 
        <div class="collection">
          <a href="#!" class="collection-item">Sprinkler
                  <span class="badge">     
                      <!-- Switch -->
                      <div class="switch">
                        <label>
                          Off
                        <input type="checkbox">
                        <span class="lever"></span>
                          On
                        </label>
                      </div>
                  </span> 
          </a>
          
        </div>
  
  </div>
<!-- Room lights and fans code ends here -->
<script>
 $(document).ready(function(){
  $(".button-collapse").sideNav();
  });
</script>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/security.html.erb

<!-- Nav Bar and Slider code begins -->
<nav class = "black ">
  <ul class="right hide-on-med-and-down">
    <a href="#" class="brand-logo center">IOT App</a>
    <!--<li><a href="#!">Second Sidebar Link</a></li> -->
  </ul>
  <ul id="slide-out" class="side-nav linepadding">
    <li> <%= link_to "Home Automation" , root_path %>  </li>
    <hr width =80%>
    <li> <%= link_to "Security", users_security_path %>  </li>
    <li > <div class="techsupport" ><hr width =80%> <div class="orange "> <%= link_to "Tech Support", users_techsupport_path %></div> </div> </li>
    
    
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons iconpadding">menu</i></a>
</nav>

<div class = "container "> 
        <h4 class ="center thin" > Home </h4> 

<div class="collection">
          <a href="#!" class="collection-item">Status
                  <span class="badge">     
                      <!-- Switch -->
                      <div class="switch">
                        <label>
                          Unlock
                        <input type="checkbox">
                        <span class="lever"></span>
                          Lock
                        </label>
                      </div>
                  </span> 
          </a>
</div>

<script>
 $(document).ready(function(){
  $(".button-collapse").sideNav();
  });
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phn:</strong>
  <%= @user.phn %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/techsupport.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="./css/materialize.min.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="./css/external.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="./css/switch.css"  media="screen,projection"/>
  
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title> Tech Support</title>
</head>

<body>
<!-- Nav Bar and Slider code begins -->
<nav class = "black ">
  <ul class="right hide-on-med-and-down">
    <a href="#" class="brand-logo center">IOT App</a>
    <!--<li><a href="#!">Second Sidebar Link</a></li> -->
  </ul>
  <ul id="slide-out" class="side-nav linepadding">
    <li> <%= link_to "Home Automation" , root_path %>  </li>
    <hr width =80%>
    <li> <%= link_to "Security", users_security_path %>  </li>
    <li > <div class="techsupport" ><hr width =80%> <div class="orange "> <%= link_to "Tech Support", users_techsupport_path %></div> </div> </li>
    
    
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons iconpadding">menu</i>lolol</a>
</nav>
<div class="row container ">
        <div class="col s12 ">
          <div class="card ">
            <div class="card-content black-text">
              <span class="card-title">Help Desk</span>
              <p> Please contact 011-32423797 for troubleshoooting.</p>
            </div>
            <div class="card-action">
              <a href="#">Click here.</a>
              
            </div>
          </div>
        </div>
      </div>
</body>
<!--Import jQuery before materialize.js-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="./js/materialize.min.js"></script>

<script>
 $(document).ready(function(){
  $(".button-collapse").sideNav();
  });
</script>

</html>